### ISSUE TITLE
systemd warning about conflicting jobs when the admin container exits

### ISSUE THREAD

**Issue by etungsten** [bottlerocket-os/bottlerocket-admin-container#62]
**Image I'm using:**
[v0.9.0](https://github.com/bottlerocket-os/bottlerocket-admin-container/releases/tag/v0.9.0)

**Issue or Feature Request:**

When exiting the admin container, the user instance of systemd will log the following into the journal which seems concerning:
```
systemd[1]: Stopping Host container: admin...
host-ctr[1648]: Requested transaction contains unmergeable jobs: Transaction contains conflicting jobs 'stop' and 'start' for systemd-exit.service. Probably contradicting requirement dependencies configured.
host-ctr[1648]: Failed to enqueue exit.target job: Transaction contains conflicting jobs 'stop' and 'start' for systemd-exit.service. Probably contradicting requirement dependencies configured.
host-ctr[1648]: time="2022-07-05T17:26:16Z" level=info msg="container task exited" code=0
systemd[1]: host-containers@admin.service: Deactivated successfully.
```

The admin container process still exits non-zero.

**Comment by markusboehme** [comment]
A path I followed for #76 happened to converge with this issue. Here's what I found: Exiting a user instance of systemd starts the `exit.target`, which depends on `systemd-exit.service`, which in turn depends on `-.slice` (the root slice) and `shutdown.target`. The stated conflict is between the latter two, with `-.slice` defining a conflict with `shutdown.target`. This can be fixed via a backport of https://github.com/systemd/systemd/pull/4477 which I'll send a PR for once #76 is merged, since it provides everything needed to build systemd for the admin container.
