### ISSUE TITLE
Should the admin container be able to run binaries in `/.bottlerocket/rootfs`?

### ISSUE THREAD

**Issue by stockholmux** [bottlerocket-os/bottlerocket-admin-container#77]
**Image I'm using:**  bottlerocket-aws-k8s-1.23-x86_64-v1.11.1

**Issue or Feature Request:** 
In the [EKS-A documentation](https://anywhere.eks.amazonaws.com/docs/tasks/packages/troubleshoot/#error-imagepullbackoff-on-package-or-package-controller), a troubleshooting item requests users to run `ctr image pull ...` . This seems to be written for a different distro. 

This can be achieved by using `sheltie` and there is an [effort to document this method](https://github.com/aws/eks-anywhere/issues/4575). Having folks use `sheltie` is not ideal for a variety of reasons.  

Since the `rootfs` is mounted in the admin container, I tried to run `ctr` (and `host-ctr` actually) from within the admin container. Doing so yields a missing shared object:

```
# pwd
/.bottlerocket/rootfs/x86_64-bottlerocket-linux-gnu/sys-root/usr/bin
# ./ctr
./ctr: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./ctr)
./ctr: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./ctr)
```

Is this intended behaviour for the admin container?

**Comment by bcressey** [comment]
This is expected behavior; there's no general way to guarantee that the dynamic linker and shared libraries in a container are compatible with the host.

Binaries like `apiclient` that are intended to run in any container are built with musl libc and statically linked to avoid this.

That approach would be quite wasteful in terms of disk space to apply distro-wide, and wouldn't really make this robust since non-ELF code like config files in `/etc` might not be compatible either.

Instead, the approach I recommend is to use something like this:
```
chroot /.bottlerocket/rootfs <command>
```

**Comment by stockholmux** [comment]
Works for me - thanks @bcressey !
